apiVersion: v2
name: firehose-ethereum
description: A Helm chart for Kubernetes
type: application
version: 0.3.1
appVersion: v2.12.1-geth
keywords:
  - firehose
  - substreams
annotations:
  lookupName: "ghcr.io/streamingfast/firehose-ethereum"
