apiVersion: v2
name: firehose-ethereum
description: A Helm chart for Kubernetes
type: application
version: 0.3.2
appVersion: v2.12.4-geth
keywords:
  - firehose
  - substreams
annotations:
  lookupName: "ghcr.io/streamingfast/firehose-ethereum"
