apiVersion: v2
name: firehose-ethereum
description: A Helm chart for Kubernetes
type: application
version: 0.3.0
appVersion: v2.11.13-geth
keywords:
  - firehose
  - substreams
annotations:
  lookupName: "ghcr.io/streamingfast/firehose-ethereum"
