chain:
  network: eth
  blocksVersion: v1

image:
  repository: ghcr.io/streamingfast/firehose-ethereum
  tag: v2.3.7
  pullPolicy: IfNotPresent



tier_1:

  nameOverride: ""
  fullnameOverride: ""

#  env:
#    ENV_VAR_1: value1
#    ENV_VAR_2: value2
#    # ... additional environment variables ...
#  
#  secretEnv:
#    SECRET_VAR_1:
#      secretName: secret-name-1
#      key: key-1
#    SECRET_VAR_2:
#      secretName: secret-name-2
#      key: key-2

  # -- Pull secrets required to fetch the Image
  imagePullSecrets: []

  service:
    type: ClusterIP
    ipFamilyPolicy: []
    clusterIP: []
    ports:
      grpc: 9000
      metrics: 9102

  # -- Set custom aliases for preconfigured commands in your environment
  aliases: {}

  # -- Additional CLI arguments to pass to `indexer-agent`
  extraArgs: []

  # Increasing the grace termination period prevents Kubernetes
  # from killing the node process prematurely. Premature shutdown
  # can lead to data integrity issues
  # -- Amount of time to wait before force-killing the process
  terminationGracePeriodSeconds: 10

  # -- Annotations for the `Pod`
  podAnnotations: {}

  # -- Pod-wide security context
  podSecurityContext: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  config: |
      common-auth-plugin: []
      common-metering-plugin: []
      common-live-blocks-addr: []
      common-merged-blocks-store-url: []
      common-one-block-store-url: []
      common-forked-blocks-store-url: []
      common-system-shutdown-signal-delay: 10s
      substreams-rpc-endpoints: []
      substreams-state-store-url: []
      substreams-tier1-grpc-listen-addr: 9000
  # -- substreams-tier1-subrequests-endpoint: Not Needed, helm attached to tier2 svc

tier_2:

  nameOverride: ""
  fullnameOverride: ""

#  env:
#    ENV_VAR_1: value1
#    ENV_VAR_2: value2
#    # ... additional environment variables ...
#  
#  secretEnv:
#    SECRET_VAR_1:
#      secretName: secret-name-1
#      key: key-1
#    SECRET_VAR_2:
#      secretName: secret-name-2
#      key: key-2


  # -- Pull secrets required to fetch the Image
  imagePullSecrets: []

  service:
    type: ClusterIP
    ipFamilyPolicy: []
    clusterIP: []
    ports:
      grpc: 9000
      metrics: 9102

  # -- Set custom aliases for preconfigured commands in your environment
  aliases: {}

  # -- Additional CLI arguments to pass to `indexer-agent`
  extraArgs: []

  # Increasing the grace termination period prevents Kubernetes
  # from killing the node process prematurely. Premature shutdown
  # can lead to data integrity issues
  # -- Amount of time to wait before force-killing the process
  terminationGracePeriodSeconds: 10

  # -- Annotations for the `Pod`
  podAnnotations: {}

  # -- Pod-wide security context
  podSecurityContext: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  config: |
    log-verbosity: 0
    common-metering-plugin: []
    common-live-blocks-addr: []
    common-merged-blocks-store-url: []
    common-one-block-store-url: []
    common-system-shutdown-signal-delay: 10s
    common-auto-mem-limit-percent: 90
    # substreams-state-bundle-size:
    substreams-state-store-url: []
    # substreams-tier2-discovery-service-url:
    substreams-tier2-grpc-listen-addr: :9000
