{{- $values := $.Values.blockmeta_sink_serve }}
{{- $componentName := "blockmeta-sink-serve" }}
{{- $componentLabel := include "blockmeta_sink_serve.componentLabelFor" $componentName }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chain.network}}-{{ include "blockmeta_sink_serve.fullname" . }}-{{ $componentName }}-{{ .Values.chain.version}}
  labels: 
    {{- include "blockmeta_sink_serve.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  replicas: {{ include "blockmeta_sink_serve.replicas" $values }}
  selector:
    matchLabels:
      {{- $componentLabel | nindent 6 }}
      {{- include "blockmeta_sink_serve.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "blockmeta_sink_serve.selectorLabels" . | nindent 8 }}
        {{- $componentLabel | nindent 8 }}
        {{- with $values.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $values.terminationGracePeriodSeconds | default "60" }}
      containers:
        - name: {{ $componentName }}
          image: "{{ .Values.blockmeta.sink.serve.image.repository }}:{{ .Values.blockmeta.sink.serve.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.blockmeta.sink.serve.image.pullPolicy }}
          args:
            - "serve"
            - "{{ .Values.tikv.url }}"
            - "{{ .Values.spkg.url }}"
            - "--listen-addr=:{{ .Values.blockmeta.sink.serve.service.ports.grpc }}"
          ports:
            - name: grpc
              containerPort: {{ .Values.blockmeta.sink.serve.service.ports.grpc }}
              protocol: TCP



