apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.chainName }}-sf-blockmeta-serve-{{ .Values.blockVersion }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app:  {{ .Values.chainName }}-sf-blockmeta-serve-{{ .Values.blockVersion }}
  replicas: 1
  template:
    metadata:
      labels:
        app:  {{ .Values.chainName }}-sf-blockmeta-serve-{{ .Values.blockVersion }}
    spec:
      containers:
        - name:  {{ .Values.chainName }}-sf-blockmeta-serve-{{ .Values.blockVersion }}
          image: {{ .Values.sinkImage }}
          args:
            - "serve"
            - "{{ .Values.tikvUrl }}"
            - "{{ .Values.spkgUrl }}"
            - "--listen-addr=:{{ .Values.servePort }}"