apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chainName }}-sf-blockmeta-serve-svc-{{ .Values.blockVersion }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.chainName }}-sf-blockmeta-serve-svc-{{ .Values.blockVersion }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ipFamilyPolicy: PreferDualStack
  clusterIP: None
  selector:
    app: {{ .Values.chainName }}-sf-blockmeta-serve-{{ .Values.blockVersion }}
  ports:
    - name: grpc
      port: {{ .Values.servePort }}
      protocol: TCP
      targetPort: grpc
