{{- $values := $.Values.blockmeta_sink_serve }}
{{- $componentName := "blockmeta-sink-serve" }}
{{- $componentLabel := include "blockmeta_sink_serve.componentLabelFor" $componentName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chain.network}}-{{ include "blockmeta_sink_serve.fullname" . }}-{{ $componentName }}-{{ .Values.chain.version }}-svc
  labels:
    {{- include "blockmeta_sink_serve.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  clusterIP: None # Headless service
  ports:
  {{- range $portName, $portNumber := $.Values.blockmeta.sink.serve.service.ports }}
    - port: {{ $portNumber }} # the port we expose on the Service, user configurable
      targetPort: {{ $portName }} # the name of the port on the container that we are routing to
      protocol: TCP
      name: {{ $portName }}
  {{- end }}
  selector:
    {{- include "blockmeta_sink_serve.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}