image:
  repository: ghcr.io/pinax-network/substreams-sink-sql
  tag: develop
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Secret to pull image from private repo
imagePullSecret: ghcr-cred

# Number of job to parallelize the filling process
jobAmount: 1
# Start and end block that will be split between all jobs
startBlock: 0
endBlock: -1
# spkg file to use
manifest: https://github.com/pinax-network/substreams-antelope-tokens/releases/download/v0.4.0/antelope-tokens-v0.4.0.spkg
dsn:
  secretName: sql-sink-dsn
  key: dsn
# environment variables to be use by the applications <key>: <value>
env:
  substreams_endpoints_config_mainnet: eos-sf-substreams-tier1-v3.service.march.consul.eosn.io:9000
  sink_sql_run_undo_buffer_size: 100
  sink_sql_run_batch_row_flush_interval: 100000
  sink_sql_run_batch_block_flush_interval: 20000
  sink_sql_run_live_block_flush_interval: 10
  sink_sql_run_on_module_hash_mistmatch: warn

command:
  - "substreams-sink-sql"
  - "run"
  - "--plaintext"
args: []