image:
  repository: ghcr.io/pinax-network/substreams-sink-sql
  tag: develop
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# nodeAffinity:
# - matchExpressions:
#   - key: kubernetes.io/hostname
#     operator: NotIn   # In or NotIn
#     values:
#       - dom85

# Secret to pull image from private repo
imagePullSecret: ghcr-cred

# Number of job to parallelize the filling process
jobAmount: 1
# Start and end block that will be split between all jobs
startBlock: 0
endBlock: -1
# spkg file to use
manifest: myFile.spkg

# Clickhouse host name
host: myClickhouseDB
# Clickhouse database to use
database: myDatabase
# Prefix to add to cursor tables being created and deleted by the backfill jobs
# By default: backprocess-<startBlock>
tablePrefix: backprocess
# Username/Password to connect to database from an existing secret
clickhouseAuth:
  secretName: ch-auth
  keyUsername: username
  keyPassword: password
# environment variables to be use by the applications <key>: <value>
env:
  substreams_endpoints_config_mainnet: mySubstreams:9000
  sink_sql_run_undo_buffer_size: 100
  sink_sql_run_batch_row_flush_interval: 100000
  sink_sql_run_batch_block_flush_interval: 20000
  sink_sql_run_live_block_flush_interval: 10
  sink_sql_run_on_module_hash_mistmatch: warn
  sink_sql_run_plaintext: true