{{- $values := $.Values.fullMode }}
{{- $componentName := "substreams-tier-1" }}
{{- $componentLabel := include "firehose-ethereum.componentLabelFor" $componentName }}
{{- if and (eq .Values.mode "full") $values.components.substreams.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $componentName }}-config
  labels:
    {{- include "firehose-ethereum.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
data:
  config.yaml: |
    start:
      args:
        - substreams-tier1
      flags:
{{- range $key, $val := $.Values.commonConfig }}
        {{ $key }}: {{ $val | quote }}
{{- end }}
{{- range $key, $val := $values.components.substreams.config }}
        {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}