{{- $values := $.Values.fullMode }}
{{- $componentName := "substreams-tier-1" }}
{{- $componentLabel := include "firehose-ethereum.componentLabelFor" $componentName }}
{{- if and (eq .Values.mode "full") $values.components.substreams.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ $componentName }}-svc
  labels:
    {{- include "firehose-ethereum.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "firehose-ethereum.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
  ports:
    - name: grpc
      port: 10016
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9102
      targetPort: metrics
      protocol: TCP
{{- end }}