{{- $values := $.Values.blockmeta_server }}
{{- $componentName := "blockmeta-server" }}
{{- $componentLabel := include "blockmeta_server.componentLabelFor" $componentName }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chain.network}}-{{ include "blockmeta_server.fullname" . }}-{{ $componentName }}-{{ .Values.chain.version}}
  labels: 
    {{- include "blockmeta_server.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  replicas: {{ include "blockmeta_server.replicas" $values }}
  selector:
    matchLabels:
      {{- $componentLabel | nindent 6 }}
      {{- include "blockmeta_server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "blockmeta_server.selectorLabels" . | nindent 8 }}
        {{- $componentLabel | nindent 8 }}
        {{- with $values.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $values.terminationGracePeriodSeconds | default "60" }}
      containers:
        - name: {{ $componentName }}
          image: "{{ .Values.blockmeta.server.image.repository }}:{{ .Values.blockmeta.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.blockmeta.server.image.pullPolicy }}
          args:
            - "./blockmeta"
            - "--sink-addr={{ .Values.chain.network}}-{{ include "blockmeta_sink_serve.fullname" . }}-{{ $componentName }}-{{ .Values.chain.version }}-svc:{{ .Values.blockmeta.sink.serve.service.ports.grpc }}"
            - "--grpc-listen-addr=:{{ .Values.blockmeta.server.service.ports.grpc }}"
            - "--auth-url={{ .Values.auth.url }}"
            - "--metering-url={{ .Values.metering.url }}"
          ports:
            - name: grpc
              containerPort: {{ .Values.blockmeta.server.service.ports.grpc }}
              protocol: TCP



