{{- $values := $.Values.server }}
{{- $componentName := "server" }}
{{- $componentLabel := include "blockmeta.componentLabelFor" $componentName | default "" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.uniqueName" . }}
  labels:
    app.kubernetes.io/name: {{ include "server.uniqueName" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "server.uniqueName" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "server.uniqueName" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with $values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $values.nodeSelector }}
      nodeSelector:
        {{- toYaml $values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $values.serviceAccount.create }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $values.terminationGracePeriodSeconds | default 60 }}
      containers:
        - name: {{ $componentName }}
          image: "{{ $.Values.image.service.repository }}:{{ $.Values.image.service.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.service.pullPolicy }}
          args:
            - "./blockmeta"
            - "--sink-addr={{ include "sink.uniqueName" . }}-svc"
            - "--grpc-listen-addr=:{{ index $values.service.ports "grpc" }}"
            - "--auth-url={{ .Values.auth.url }}"
            - "--metering-url={{ .Values.metering.url }}"
            {{- range $arg := $values.extraArgs }}
            - {{ $arg }}
            {{- end }}
          ports:
            - name: grpc
              containerPort: {{ index $values.service.ports "grpc" }}
              protocol: TCP
