{{- $values := $.Values.server }}
{{- $componentName := "server" }}
{{- $componentLabel := include "blockmeta.componentLabelFor" $componentName }}
{{- if $values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "server.uniqueName" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "server.uniqueName" . }}-ingress
  annotations:
    {{- with $values.ingress.ingressClassName }}
    kubernetes.io/ingress.class: {{ . | quote }}
    {{- end }}
    {{- with $values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if $values.ingress.ingressClassName }}
  ingressClassName: {{ $values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
  - host: {{ $values.ingress.host | quote }}
    http:
      paths:
      {{- range $portName, $portNumber := $values.service.ports }}
      - path: {{ $values.ingress.paths.default | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "server.uniqueName" $ }}-svc
            port:
              name: {{ $portName }}
      {{- end }}
  {{- if $values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ $values.ingress.host | quote }}
    secretName: {{ $values.ingress.tls.secretName | default (printf "%s-tls" (include "server.uniqueName" .)) }}
  {{- end }}
{{- end }}