{{- $values := $.Values.server }}
{{- $componentName := "server" }}
{{- $componentLabel := include "blockmeta.componentLabelFor" $componentName }}

{{- if $values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "server.uniqueName" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "server.uniqueName" . }}-ingress
  annotations:
    {{- range $key, $value := $values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if $values.ingress.tls }}
  tls:
    - hosts:
        {{- range $host := $values.ingress.hosts }}
        - {{ $host }}
        {{- end }}
      secretName: {{ $values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- range $host := $values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          {{- range $path := $values.ingress.paths }}
          - path: {{ $path.path }}
            pathType: {{ $path.pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ include "server.uniqueName" . }}-svc
                port:
                  number: {{ $path.port }}
          {{- end }}
    {{- end }}
{{- end }}
