{{- $values := $.Values.tier_1 }}
{{- $componentName := "tier-1" }}
{{- $componentLabel := include "substreams.componentLabelFor" $componentName }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if $values.service.topologyAwareRouting.enabled }}
  annotations:
    {{- if semverCompare ">= 1.27-0" .Capabilities.KubeVersion.GitVersion }}
    service.kubernetes.io/topology-mode: "auto"
    {{- else }}
    service.kubernetes.io/topology-aware-hints: "auto"
    {{- end }}
  {{- end }}
  name: {{ .Values.chain.network }}-{{ include "substreams.fullname" . }}-{{ $componentName }}-{{ .Values.chain.blocksVersion }}-svc
  labels:
    {{- include "substreams.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  type: {{ $values.service.type }}
  ports:
  {{- range $portName, $portNumber := $values.service.ports }}
    - port: {{ $portNumber }} # the port we expose on the Service, user configurable
      targetPort: {{ $portName }} # the name of the port on the container that we are routing to
      protocol: TCP
      name: {{ $portName }}
  {{- end }}
  selector:
    {{- include "substreams.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}