apiVersion: apps/v1
kind: {{ if .Values.pvc.enabled }}StatefulSet{{ else }}Deployment{{ end }}
metadata:
  name: {{ include "substreams-sink.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "substreams-sink.common-labels" . | nindent 4 }}
    {{- include "substreams-sink.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "substreams-sink.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "substreams-sink.common-labels" . | nindent 8 }}
        {{- include "substreams-sink.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "substreams-sink.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        {{- if .Values.args }}
        args: {{ .Values.args }}
        {{- end }}
        ports:
        - containerPort: {{ if hasKey .Values.env "port" }}{{ .Values.env.port | default .Values.service.port }}{{ else }}{{ .Values.service.port }}{{ end }}
        envFrom:
        - configMapRef:
            name: env-{{ include "substreams-sink.fullname" . }}
        {{- if .Values.secret.secretName }}
        - secretRef:
            name: {{ .Values.secret.secretName }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ if hasKey .Values.env "port" }}{{ .Values.env.port | default .Values.service.port }}{{ else }}{{ .Values.service.port }}{{ end }}
            {{- with .Values.livenessProbe }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            periodSeconds: {{ .periodSeconds }}
            {{- end }}
        {{- end }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.pvc.enabled }}
        volumeMounts:
            - name: cursor-volume
              mountPath: {{ .Values.volumeMountPath }}
      volumes:
        - name: cursor-volume
          persistentVolumeClaim:
            claimName: pvc-{{ include "substreams-sink.fullname" . }}
      {{- end }}