{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ include "substreams-sink.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "substreams-sink.common-labels" . | nindent 4 }}
spec:
  {{- with .Values.pvc }}
  storageClassName: {{ .storageClassName }}
  accessModes: {{ .accessModes }}
  resources:
    requests:
      storage: {{ .storage }}
  {{- end }}
{{- end }}