apiVersion: v1
kind: Service
metadata:
  name: sink
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "substreams-sink.common-labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "substreams-sink.common-labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.port }}