apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "substreams-sink-prometheus.fullname" . }}- {{- .Values.chain }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "substreams-sink-prometheus.fullname" . }}
    chain: {{ .Values.chain }}
spec:
  selector:
    matchLabels:
      app: {{ include "substreams-sink-prometheus.fullname" . }}
      chain: {{ .Values.chain }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "substreams-sink-prometheus.fullname" . }}
        chain: {{ .Values.chain }}
    spec:
      containers:
      - name: {{ include "substreams-sink-prometheus.fullname" . }}- {{- .Values.chain }}
        image: {{ .Values.image -}} : {{- .Values.tag }}
        args: ["run"]
        ports:
        - containerPort: {{ .Values.env.port }}
        envFrom:
        - configMapRef:
            name: env
        - secretRef:
            name: {{ .Values.secretName }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.env.port }}
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 5
        {{- if .Values.cursorPvc.enabled }}
        volumeMounts:
            - name: cursor-volume
              mountPath: /cursor
      volumes:
        - name: cursor-volume
          persistentVolumeClaim:
            claimName: {{ include "substreams-sink-prometheus.fullname" . }}- {{- .Values.chain }}
      {{- end }}