apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: substreams-sink-prometheus{{ if .Values.sort }}-{{ .Values.sort }}{{ end }}-{{ .Values.chain }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: substreams-sink-prometheus
    chain: {{ .Values.chain }}
spec:
  selector:
    matchLabels:
      app: substreams-sink-prometheus
      chain: {{ .Values.chain }}
  replicas: 1
  template:
    metadata:
      labels:
        app: substreams-sink-prometheus
        chain: {{ .Values.chain }}
    spec:
      containers:
      - name: substreams-sink-prometheus{{ if .Values.type }}{{ .Values.type }}{{ end }}-{{ .Values.chain }}
        image: {{ .Values.image -}} :{{ .Values.tag }}
        args: ["run"]
        ports:
        - containerPort: {{ .Values.env.port }}
        envFrom:
        - configMapRef:
            name: env-{{ .Values.chain }}
        - secretRef:
            name: {{ .Values.secretName }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.env.port }}
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 5
        {{- if .Values.cursorPvc.enabled }}
        volumeMounts:
            - name: cursor-volume
              mountPath: /cursor
      volumes:
        - name: cursor-volume
          persistentVolumeClaim:
            claimName: substreams-sink-prometheus{{ if .Values.type }}{{ .Values.type }}{{ end }}-{{ .Values.chain }}
      {{- end }}