{{- if .Values.cursorPvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: substreams-sink-prometheus{{ if .Values.type }}{{ .Values.type }}{{ end }}-{{ .Values.chain }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: substreams-sink-prometheus
    chain: {{ .Values.chain }}
    type: {{ .Values.type }}
spec:
  storageClassName: {{ .Values.cursorPvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}