{{- if .Values.cursorPvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "substreams-sink-prometheus.fullname" . }}- {{- .Values.chain }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "substreams-sink-prometheus.fullname" . }}
    chain: {{ .Values.chain }}
spec:
  storageClassName: {{ .Values.cursorPvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}