apiVersion: v1
kind: Service
metadata:
  name: {{ include "substreams-sink-prometheus.fullname" . }}- {{- .Values.chain }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "substreams-sink-prometheus.fullname" . }}
    chain: {{ .Values.chain }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "substreams-sink-prometheus.fullname" . }}
    chain: {{ .Values.chain }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.port }}