apiVersion: v1
kind: Service
metadata:
  name: substreams-sink-prometheus{{ if .Values.type }}{{ .Values.type }}{{ end }}-{{ .Values.chain }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: substreams-sink-prometheus
    chain: {{ .Values.chain }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: substreams-sink-prometheus
    chain: {{ .Values.chain }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.port }}