nameOverride: ""
fullnameOverride: ""

replicaCount: 1
image: ghcr.io/pinax-network/substreams-sink-prometheus
tag: v0.7.11
args: ""
# args: ["run"]

sinkType: ""
chain: ""

env:
  substreams_endpoint: ""
  manifest: ""
  module_name: ""
  start_block: ""
  stop_block: ""
  # cursor_file: "/cursor/cursor.lock"
  # production_mode: true
  # hostname: 0.0.0.0
  # port: 9102
  # verbose: true

# SUBSTREAMS_API_KEY
secretName: token-secret

livenessProbe:
  enabled: false
  path: /health

service:
  type: ClusterIP

cursorPvc:
  # if true, set cursor_file: "/cursor/cursor.lock"
  enabled: false
  storageClassName: mayastor-ext4