apiVersion: v2
name: substreams-tier-2
description: A Helm chart for deploying substreams-tier-2
type: application
version: 0.0.4
appVersion: v2.11.12
keywords:
  - substreams-tier-2
  - firehose-ethereum
annotations:
  lookupName: "ghcr.io/streamingfast/firehose-ethereum"
