{{- if .Values.serviceAccount.create }}
{{- $values := $.Values.substreams_sink_noop }}
{{- $componentName := "substreams-sink-noop" }}
{{- $componentLabel := include "substreams_sink_noop.componentLabelFor" $componentName }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "substreams_sink_noop.fullname" . }}-{{ $componentName }}-sa
  labels:
    {{- include "substreams_sink_noop.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}