{{- $values := .Values.noop }}
{{- $networkName := $values.networkName | default "ethereum" }}
{{- $componentName := printf "noop-%s" $networkName }}
{{- $componentLabel := include "noop.componentLabelFor" $componentName  | default "" }}


apiVersion: v1
kind: Service
metadata:
  name: {{ include "noop.uniqueName" . }}-svc
  labels:
    app.kubernetes.io/name: {{ include "noop.uniqueName" . }}-svc
spec:
  type: {{ .Values.noop.service.type }}
  {{- if .Values.noop.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.noop.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.noop.service.clusterIP }}
  clusterIP: {{ .Values.noop.service.clusterIP }}
  {{- end }}
  ports:
    - name: grpc
      port: {{ .Values.noop.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: {{ .Values.noop.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "noop.uniqueName" . }}


---
{{- if .Values.noop.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "noop.uniqueName" . }}-monitor
  labels:
    {{- include "noop.labels" . | nindent 4 }}
spec:
  endpoints:
    - honorLabels: true
      interval: {{ .Values.noop.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.noop.serviceMonitor.scrapeTimeout | default "10s" }}
      port: metrics
      path: /metrics
      relabelings:
      - action: replace
        sourceLabels: [__meta_kubernetes_pod_label_app]
        targetLabel: app
      - action: replace
        sourceLabels: [__meta_kubernetes_pod_label_block_version]
        targetLabel: block_version
      - action: replace
        sourceLabels: [__meta_kubernetes_pod_label_network]
        targetLabel: network
      - action: replace
        sourceLabels: [__meta_kubernetes_pod_label_sf_type]
        targetLabel: sf_type
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "noop.uniqueName" . }}-svc
{{- end }}