{{- if .Values.serviceAccount.create }}
{{- $values := .Values.noop }}
{{- $networkName := $values.networkName | default "ethereum" }}
{{- $componentName := printf "noop-%s" $networkName }}
{{- $componentLabel := include "noop.componentLabelFor" $componentName  | default "" }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "noop.uniqueName" . }}-sa
  labels:
    {{- include "noop.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}