apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chainName }}-sf-blockmeta-inject-svc-{{ .Values.blockVersion }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.chainName }}-sf-blockmeta-inject-svc-{{ .Values.blockVersion }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ipFamilyPolicy: PreferDualStack
  clusterIP: None
  selector:
    app: {{ .Values.chainName }}-sf-blockmeta-inject-{{ .Values.blockVersion }}
  ports:
    - name: prom
      port: {{ .Values.injectMetricsPort }}
      protocol: TCP
      targetPort: prom