apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.apitype }}
    app: {{ .Values.apitype }}
    {{- end }}
    {{- include "api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- if .Values.apitype }}
        app: {{ .Values.apitype }}
        {{- end }}
        {{- include "api.labels" . | nindent 8 }}
    spec:
      {{- if .Values.initContainer.enabled }}
      initContainers:
        - name: schema-init
          image: curlimages/curl:8.6.0
          command: ["/bin/sh", "-c", "/scripts/schema-init.sh"]
          volumeMounts:
          - name: script-volume
            mountPath: /scripts
      {{- end }}
      containers:
      - name: {{ include "api.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.env.port }}
        envFrom:
        - configMapRef:
            name: env-{{ include "api.fullname" . }}
        {{- if .Values.secret.secretName }}
        - secretRef:
            name: {{ .Values.secret.secretName }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ if hasKey .Values.env "port" }}{{ .Values.env.port | default .Values.service.port }}{{ else }}{{ .Values.service.port }}{{ end }}
            {{- with .Values.livenessProbe }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            periodSeconds: {{ .periodSeconds }}
            {{- end }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.initContainer.enabled }}
      volumes:
      - name: script-volume
        configMap:
          name: schema-init-{{ include "api.fullname" . }}
          defaultMode: 0777
      {{- end }}