apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "api.fullname" . }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints }}
  routes:
    - match: {{ .Values.ingress.match }}
      kind: Rule
      services:
        - name: {{ include "api.fullname" . }}
          port: {{ .Values.service.port }}
