{{- if .Values.secret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{- range $key, $val := .Values.secret.secrets }}
    {{- if $val }}
    {{ $key | upper }}: {{ $val  | quote }}
    {{- end }}
    {{- end }}
    metadata:
      creationTimestamp: null
      name: {{ .Values.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}