apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
spec:
  selector:
    app: {{ include "api.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.port }}