apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "substreams-sink-clickhouse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image -}} : {{- .Values.tag }}
        ports:
        - containerPort: {{ .Values.env.port }}
        envFrom:
        - configMapRef:
            name: env
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.env.port }}
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 5
