{{- $values := $.Values.substreams }}
{{- $componentName := "tier-1" }}
{{- $componentLabel := include "substreams.componentLabelFor" $componentName }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "substreams.uniqueName" . }}-svc
  labels:
    {{ include "substreams.uniqueName" . }}-svc
spec:
  {{- with $values.service.type }}
  type: {{ . }}
  {{- else }}
  type: ClusterIP
  {{- end }}
  {{- with $values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with $values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  ports:
  {{- range $portName, $portNumber := $values.service.ports }}
    - port: {{ $portNumber }} # the port we expose on the Service, user configurable
      targetPort: {{ $portName }} # the name of the port on the container that we are routing to
      protocol: TCP
      name: {{ $portName }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "substreams.uniqueName" . }}

---
{{- if .Values.substreams.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "substreams.uniqueName" . }}-monitor
  labels:
    {{- include "substreams.labels" . | nindent 4 }}
spec:
  endpoints:
    - honorLabels: true
      interval: {{ .Values.substreams.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.substreams.serviceMonitor.scrapeTimeout | default "10s" }}
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "substreams.uniqueName" . }}-svc
{{- end }}

