apiVersion: v2
name: firehose-core
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: v1.10.1
keywords:
  - firehose
  - substreams
annotations:
  lookupName: "ghcr.io/streamingfast/firehose-core"
