{{- $values := $.Values.substreams_tier_2 }}
{{- $componentName := "substreams-tier-2" }}
{{- $componentLabel := include "substreams_tier_2.componentLabelFor" $componentName }}

apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "substreams_tier_2.fullname" . }}-{{ $componentName }}-config
data:
  config.yaml: |
    start:
      args:
        - substreams-tier2
      flags:
      {{- toYaml (fromYaml (printf "%s" $values.config)) | nindent 8 }}