{{- if .Values.serviceAccount.create }}
{{- $values := $.Values.substreams_tier_2 }}
{{- $componentName := "substreams-tier-2" }}
{{- $componentLabel := include "substreams_tier_2.componentLabelFor" $componentName }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "substreams_tier_2.fullname" . }}-{{ $componentName }}-sa
  labels:
    {{- include "substreams_tier_2.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}