{{- $values := $.Values.fullMode }}
{{- if and (eq .Values.mode "full") $values.components.reader.enabled }}
{{- $componentName := "reader" }}
{{- $componentLabel := include "firehose-ethereum.componentLabelFor" $componentName }}
{{- $jwt := printf "%s%s" (uuidv4 | replace "-" "") (uuidv4 | replace "-" "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-firehose-jwt
  labels:
    {{- include "firehose-ethereum.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
type: Opaque
data:
  jwt.hex: {{ $jwt | b64enc }}
{{- end }}