{{- $values := $.Values.server }}
{{- $componentName := "inject" }}
{{- $componentLabel := include "blockmeta.componentLabelFor" $componentName | default "" }}


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inject.uniqueName" . }}
  labels:
    app.kubernetes.io/name: {{ include "inject.uniqueName" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "inject.uniqueName" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "inject.uniqueName" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with $values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $values.nodeSelector }}
      nodeSelector:
        {{- toYaml $values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $values.serviceAccount.create }}
      serviceAccountName: {{ include "inject.serviceAccountName" . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $values.terminationGracePeriodSeconds | default 60 }}
      containers:
        - name: {{ $componentName }}
          image: "{{ $.Values.image.sink.repository }}:{{ $.Values.image.sink.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.sink.pullPolicy }}
          args:
            - "inject"
            - "{{ .Values.substreams_tier1.url}}"
            - "{{ .Values.tikv.url}}"
            - "{{ .Values.spkg.url }}"
            - "--metrics-listen-addr=:{{ index $values.service.ports "metrics" }}"
            - "--plaintext"
            {{- range $arg := $values.extraArgs }}
            - {{ $arg }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ index $values.service.ports "metrics" }}
              protocol: TCP
