name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: 'main' # Checkout main branch to get the latest changes

      - name: Download latest release assets
        id: download_assets
        run: |
          ASSET_URL=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | jq -r '.assets[] | select(.name | endswith(".tgz")).browser_download_url')
          wget $ASSET_URL -O latest_release.tgz

      - name: Copy .tgz file to gh-pages branch
        run: |
          cp latest_release.tgz ./helm-charts/

      - name: Commit and push changes to gh-pages branch
        uses: EndBug/add-and-commit@v7
        with:
          add: 'helm-charts/latest_release.tgz'
          message: 'Update charts'
          branch: 'gh-pages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
