name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Download release asset
        run: |
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          RELEASE_ID=$(echo "${{ github.event.release.id }}")
          RELEASE_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/releases/${RELEASE_ID}"
          echo "Release URL: $RELEASE_URL"
          ASSET_URL=$(curl -s $RELEASE_URL | jq -r '.assets[] | select(.name | endswith(".tgz")).browser_download_url')
          echo "Asset URL: $ASSET_URL"
          wget $ASSET_URL -O latest_release.tgz

      - name: Copy .tgz file to gh-pages branch root
        run: |
          cp latest_release.tgz $GITHUB_WORKSPACE/../

      - name: Commit and push changes to gh-pages branch
        uses: EndBug/add-and-commit@v7
        with:
          add: 'latest_release.tgz'
          message: 'Update charts'
          branch: 'gh-pages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
