name: Helm Chart Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Helm
        uses: azure/setup-helm@v2
        with:
          version: 'v3.7.0' # Update with the desired Helm version
      
      - name: Generate Index.yaml
        run: |
          helm repo index --url https://your-repo-url.com/ .
      
      - name: Package Helm Charts
        run: |
          cd charts
          for chart_dir in */; do
            helm package $chart_dir
          done
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Release ${{ github.sha }}
          draft: false
          prerelease: false
      
      - name: Upload Charts to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./charts/*.tgz
          asset_name: ${{ github.sha }}-${{ github.run_number }}.tgz
          asset_content_type: application/x-compressed-tar