name: Update Helm Repository

on:
  release:
    types: [published]

jobs:
  call-update-helm-repo-stable:
    uses: ./.github/workflows/update-helm-repo.yaml
    permissions:
      contents: write # for updating index.yaml
    with:
      repo: stable
