apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace.name }}-quota
  namespace: {{ .Values.namespace.name }}
spec:
  hard:
    requests.cpu: {{ .Values.namespace.cpuLimit | quote }}
    requests.memory: {{ .Values.namespace.memoryLimit | quote }}
    limits.cpu: {{ .Values.namespace.cpuLimit | quote }}
    limits.memory: {{ .Values.namespace.memoryLimit | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace.name }}-limit-range
  namespace: {{ .Values.namespace.name }}
spec:
  limits:
  - default:
      cpu: 50m
      memory: 64Mi
    defaultRequest:
      cpu: 40m
      memory: 64Mi
    type: Container